---
title: "pset7"
author: "izd3"
format: pdf
editor: visual
---

1\.

\(a\)

0 will be considered equilibria as it is considered a special condition in order to find the other equilibria we do r(x)f(z)=p and solve for z:

$$
z(9-9z)=2->9z-9z^2=2->9z^2-9z-2=0->-(3z-1)(3z-2)=0
$$

$$
3z-1=0->z=\frac{1}{3}
$$

$$
3z-2=0->z=\frac{2}{3}
$$

Therefore all the equilibria possioble are z=0, 1/3, and 2/3

\(b\)

In this case, z=2/3 would be and z=0. 0 is stable because if anyone makes a guess close to 0 it would naturally decline to 0 and z=2/3 is stable because If slightly more than 2/3 fraction buys the good, then the demand gets pushed back towards 2/3; if slightly less than 2/3 fraction buys the good, then the demand correspondingly gets pushed up toward 2/3. So in the event of a "near miss" in the population's expectations around 2/3, we would expect the outcome to settle down to 2/3 anyway.

\newpage

2\.

a\)

0 will be considered equilibria as it is considered a special condition in order to find the other equilibria we do r(x)f(z)=p and solve for z:

$$
6(1-z)*2z=\frac{3}{2}->12(1-z)z=\frac{3}{2}->z-z^2=\frac{1}{8}->z-z^2-\frac{1}{8}
$$

$$
-8z^2+8z-1=0
$$

using quadratic formula we get

$$
z\approx0.85\,and\,z\approx0.15
$$

Therefore possible equilibriums are z=0,15,0.85

\(b\) If the fraction of potential users who are actually using the product is 1/2, we can plug this into the reservation price function to see what happens:-

$$
r(x)f(z)=6(1-x)2(\frac{1}{2})
$$

$$
r(x)f(z)=6(1-x)
$$

$$
6(1-x)=\frac{3}{2}
$$

$$
1-x=\frac{1}{4}
$$

$$
x=\frac{3}{4}
$$

So, the fraction of users will converge to 3/4 over time.

c\)

To find the maximum price *p* the company could charge for a positive equilibrium fraction of users, we need to find the price at which the consumer with the lowest reservation price **(x=0)** is just willing to pay for the product when everyone else is using it **(z=1)** :-

$$
r(0)f(1)=p
$$

$$
6(1-0)2(1)=p->12=p
$$

Whether it would be a good idea to increase the price to *p*− depends on various factors such as the elasticity of demand, the competitive environment, and the potential for backlash from consumers. If the demand is inelastic and the company has a monopoly over a highly desired product, it could potentially increase the price.

However, if the price increase leads to a significant drop in users, the network effects that add value to the product could be diminished, leading to a worse outcome for both the company and its users. Therefore, the company should carefully consider the potential consequences before deciding to increase the price.

\newpage

3.)

a\)

In this network, there are only two possibilities for node z:

1\. Node z has 0 in-links (followers) because there is only one outbound link per webpage, and z is randomly selected from the network.

2\. Node z has 1 in-link (follower) because it is guaranteed to be linked by the webpage y.

So, the probabilities for node z to have exactly k in-links are:

\- P(z has 0 in-links) = 1/6 (since z can be any webpage in the network).

\- P(z has 1 in-link) = 5/6 (since there are 5 other webpages that could be linked to z).

b\)

Node y, by definition, is the webpage that z links to. In this network, z has exactly one outbound link. Therefore, node y can only have 1 in-link (the link from z). The probability of node y having 1 in-link is 1.

c\)

Node y has fewer average in-links than z. This is because, in this specific network, z is guaranteed to have 1 in-link (from y), while y can only have 1 in-link (from z). On average, the pages z links to (y) have fewer in-links than z itself.

d\)

The result in (c) may not necessarily hold for all networks. It depends on the structure and characteristics of the specific network. In this case, we have a very simple network with only one outbound link per webpage. In more complex networks with varying degrees of connectivity, the relationship between average in-links for z and y may differ. The friendship paradox in networks often depends on network topology and degree distribution.

\newpage

4\.

a\) We have been given that there are 8000 articles receiving 25 views and 2000 articles receiving 50 views. The number of articles each day that receive k views is assumed to be c/k\^α.

Using this information, we can set up two equations:

$$
8000=\frac{c}{25^\alpha}
$$

$$
200=\frac{c}{50^\alpha}
$$

From equation 1:

$$
c=8000*25^\alpha
$$

Now, substitute the value of c into equation 2:

$$
200=\frac{(8000*25^\alpha)}{50^\alpha}
$$

Now, simplify and solve for α:

$$
8000*(\frac{1}{2})^\alpha
$$

Dividing both sides by 8000:

$$
\frac{1}{4}=(\frac{1}{2})^\alpha
$$

Taking the logarithm of both sides (base 2): log₂(1/4) = log₂(1/2)\^α -2 = -α

$$
log_2(\frac{1}{4})=log_2(\frac{1}{2})^\alpha-2=-\alpha\
$$

So, α = 2.

The exponent of the power law distribution determines the shape of the distribution. A higher exponent indicates that there is a greater concentration of views in a few articles, while a lower exponent indicates that the views are more evenly distributed.To estimate the exponent of the power law distribution, we can use the maximum likelihood estimation method. This method involves finding the value of the exponent that maximizes the probability of the observed data.

b\) To estimate the number of articles that receive 200 views, we can use the formula c/k\^α:

$$
\frac{c}{200^2}=\frac{8000}{50^2}=\frac{2000}{50^2}
$$

So, the number of articles receiving 200 views would be:

$$
\frac{c}{200^2}
$$

We are given that there are 8000 articles that receive 25 views. Since the power law distribution is scale-free, we can assume that the same number of articles will receive 200 views, 400 views, and so on. Therefore, the estimated number of articles that receive 200 views is 8000.

Once we have estimated the exponent of the power law distribution, we can use it to estimate the number of articles that receive a certain number of views.

c\) The popularity index of a news article is defined as:

$$
p=\frac{k}{2}
$$

Therefore, the fraction of articles with a popularity index value of p is equal to the fraction of articles that receive 2p views. Using the power law distribution, we can write the following equation:

$$
f(p)=\frac{c}{(2p)^a}
$$where f(p) is the fraction of articles with a popularity index value of p.

The popularity index of a news article is a measure of its relative popularity

d\) To determine the parameters d and B in the following equation:

$$
f(p)=\frac{d}{(p+B)^B}
$$

we can use the following approximation for the power law distribution:

$$
f(p)=\frac{d}{(p+B)^B}\approx\frac{d}{p^B}
$$

This approximation is valid for popular articles with high p, where p=k/2 is large.

Substituting the equation for f(p) from Question (c), we get:

$$
\frac{d}{p^B}=\frac{c}{(2p)^a}
$$

Solving for d and B, we get:

$$
d=\frac{c}{}2^a\,\,B=2a
$$

The power law distribution is a useful model for describing the distribution of news article views. It is characterized by a long tail, which means that a few articles receive a large number of views, while most articles receive a relatively small number of views.

Using the power law distribution, we can estimate the number of articles that receive a certain number of views. We can also calculate the popularity index of a news article, which is a measure of its relative popularity.
